TODOListApi\Domain\TodoItem:
  type: entity
  repositoryClass: TODOListApi\Domain\TodolistRepository
  table: todo_items
  indexes:
    due_at_index:
      columns: [ due_at ]
    reporter_index:
      columns: [ reporter ]
    category_index:
      columns: [ category ]
    status_index:
      columns: [ status ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
    dueAt:
      type: date
      nullable: true
      column: due_at
    title:
      type: string
      length: 255
    description:
      type: text
    reporter:
      type: string
      length: 255
    complexity:
      type: integer
      nullable: true
    category:
      type: string
      length: 255
      nullable: true
    status:
      type: string
      length: 255